### PR TITLE
Movement, Jump n' Dash

### PR DESCRIPTION
**Pull request by JDOBrito**
Analysis and modification of the game player. Move, jump, double jump, dash.

### CODE REVIEW

**Comment by JDOBrito** [comment]
[Andar](https://trello.com/c/tvI3gi8L/9-andar)

**Comment by JDOBrito** [comment]
[Pulo Simples](https://trello.com/c/bv7pkyE2/11-pulo-simples)

**Comment by JDOBrito** [comment]
[Pulo Duplo](https://trello.com/c/I3GsFyF7/12-pulo-duplo)

**Comment by JDOBrito** [comment]
[Correr (Dash)](https://trello.com/c/Kf2yQ3As/10-correr-dash)

**Comment by AlairtonSilva** [comment]
[RF015 - Alvo Branco](https://trello.com/c/BWGbaXPl/15-rf015-alvo-branco)

**Pull request merged**
